// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NettyMsg.proto

package com.tequeno.netty.protobuf;

public final class NettyMsg {
  private NettyMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Wrapper_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Wrapper_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Request_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\016NettyMsg.proto\"\305\001\n\007Wrapper\022#\n\010dataType" +
      "\030\001 \001(\0162\021.Wrapper.DataType\022\014\n\004code\030\002 \001(\t\022" +
      "\013\n\003msg\030\003 \001(\t\022\027\n\003req\030\004 \001(\0132\010.RequestH\000\022\030\n" +
      "\003res\030\005 \001(\0132\t.ResponseH\000\022\035\n\013requestList\030\006" +
      " \003(\0132\010.Request\"\034\n\010DataType\022\007\n\003REQ\020\000\022\007\n\003R" +
      "ES\020\001B\n\n\010dataBody\"%\n\007Request\022\013\n\003key\030\001 \001(\t" +
      "\022\r\n\005value\030\002 \001(\t\"&\n\010Response\022\013\n\003key\030\001 \001(\t" +
      "\022\r\n\005value\030\002 \001(\tB7\n\'com.tequeno.bootassem" +
      "bly.netty.protobufB\010NettyMsgH\001P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Wrapper_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Wrapper_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Wrapper_descriptor,
        new String[] { "DataType", "Code", "Msg", "Req", "Res", "RequestList", "DataBody", });
    internal_static_Request_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Request_descriptor,
        new String[] { "Key", "Value", });
    internal_static_Response_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Response_descriptor,
        new String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
