// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NettyMsg.proto

package com.tequeno.netty.protobuf;

/**
 * <pre>
 * 其他message的管理者
 * </pre>
 *
 * Protobuf type {@code Wrapper}
 */
public final class Wrapper extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Wrapper)
    WrapperOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Wrapper.newBuilder() to construct.
  private Wrapper(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Wrapper() {
    dataType_ = 0;
    code_ = "";
    msg_ = "";
    requestList_ = java.util.Collections.emptyList();
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new Wrapper();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Wrapper(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();

            dataType_ = rawValue;
            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();

            code_ = s;
            break;
          }
          case 26: {
            String s = input.readStringRequireUtf8();

            msg_ = s;
            break;
          }
          case 34: {
            com.tequeno.netty.protobuf.Request.Builder subBuilder = null;
            if (dataBodyCase_ == 4) {
              subBuilder = ((com.tequeno.netty.protobuf.Request) dataBody_).toBuilder();
            }
            dataBody_ =
                input.readMessage(com.tequeno.netty.protobuf.Request.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.tequeno.netty.protobuf.Request) dataBody_);
              dataBody_ = subBuilder.buildPartial();
            }
            dataBodyCase_ = 4;
            break;
          }
          case 42: {
            com.tequeno.netty.protobuf.Response.Builder subBuilder = null;
            if (dataBodyCase_ == 5) {
              subBuilder = ((com.tequeno.netty.protobuf.Response) dataBody_).toBuilder();
            }
            dataBody_ =
                input.readMessage(com.tequeno.netty.protobuf.Response.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.tequeno.netty.protobuf.Response) dataBody_);
              dataBody_ = subBuilder.buildPartial();
            }
            dataBodyCase_ = 5;
            break;
          }
          case 50: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              requestList_ = new java.util.ArrayList<com.tequeno.netty.protobuf.Request>();
              mutable_bitField0_ |= 0x00000001;
            }
            requestList_.add(
                input.readMessage(com.tequeno.netty.protobuf.Request.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        requestList_ = java.util.Collections.unmodifiableList(requestList_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.tequeno.netty.protobuf.NettyMsg.internal_static_Wrapper_descriptor;
  }

  @Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.tequeno.netty.protobuf.NettyMsg.internal_static_Wrapper_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.tequeno.netty.protobuf.Wrapper.class, com.tequeno.netty.protobuf.Wrapper.Builder.class);
  }

  /**
   * <pre>
   * 相当于一个message即Wrapper内的一个内部类
   * </pre>
   *
   * Protobuf enum {@code Wrapper.DataType}
   */
  public enum DataType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>REQ = 0;</code>
     */
    REQ(0),
    /**
     * <code>RES = 1;</code>
     */
    RES(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>REQ = 0;</code>
     */
    public static final int REQ_VALUE = 0;
    /**
     * <code>RES = 1;</code>
     */
    public static final int RES_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static DataType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static DataType forNumber(int value) {
      switch (value) {
        case 0: return REQ;
        case 1: return RES;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<DataType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        DataType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<DataType>() {
            public DataType findValueByNumber(int number) {
              return DataType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.tequeno.netty.protobuf.Wrapper.getDescriptor().getEnumTypes().get(0);
    }

    private static final DataType[] VALUES = values();

    public static DataType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private DataType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:Wrapper.DataType)
  }

  private int dataBodyCase_ = 0;
  private Object dataBody_;
  public enum DataBodyCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    REQ(4),
    RES(5),
    DATABODY_NOT_SET(0);
    private final int value;
    private DataBodyCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static DataBodyCase valueOf(int value) {
      return forNumber(value);
    }

    public static DataBodyCase forNumber(int value) {
      switch (value) {
        case 4: return REQ;
        case 5: return RES;
        case 0: return DATABODY_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public DataBodyCase
  getDataBodyCase() {
    return DataBodyCase.forNumber(
        dataBodyCase_);
  }

  public static final int DATATYPE_FIELD_NUMBER = 1;
  private int dataType_;
  /**
   * <pre>
   * 设置数据的类型 方便得到数据后根据类型判断 非必要
   * </pre>
   *
   * <code>.Wrapper.DataType dataType = 1;</code>
   * @return The enum numeric value on the wire for dataType.
   */
  @Override public int getDataTypeValue() {
    return dataType_;
  }
  /**
   * <pre>
   * 设置数据的类型 方便得到数据后根据类型判断 非必要
   * </pre>
   *
   * <code>.Wrapper.DataType dataType = 1;</code>
   * @return The dataType.
   */
  @Override public com.tequeno.netty.protobuf.Wrapper.DataType getDataType() {
    @SuppressWarnings("deprecation")
    com.tequeno.netty.protobuf.Wrapper.DataType result = com.tequeno.netty.protobuf.Wrapper.DataType.valueOf(dataType_);
    return result == null ? com.tequeno.netty.protobuf.Wrapper.DataType.UNRECOGNIZED : result;
  }

  public static final int CODE_FIELD_NUMBER = 2;
  private volatile Object code_;
  /**
   * <code>string code = 2;</code>
   * @return The code.
   */
  @Override
  public String getCode() {
    Object ref = code_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      code_ = s;
      return s;
    }
  }
  /**
   * <code>string code = 2;</code>
   * @return The bytes for code.
   */
  @Override
  public com.google.protobuf.ByteString
      getCodeBytes() {
    Object ref = code_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      code_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MSG_FIELD_NUMBER = 3;
  private volatile Object msg_;
  /**
   * <code>string msg = 3;</code>
   * @return The msg.
   */
  @Override
  public String getMsg() {
    Object ref = msg_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      msg_ = s;
      return s;
    }
  }
  /**
   * <code>string msg = 3;</code>
   * @return The bytes for msg.
   */
  @Override
  public com.google.protobuf.ByteString
      getMsgBytes() {
    Object ref = msg_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      msg_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int REQ_FIELD_NUMBER = 4;
  /**
   * <code>.Request req = 4;</code>
   * @return Whether the req field is set.
   */
  @Override
  public boolean hasReq() {
    return dataBodyCase_ == 4;
  }
  /**
   * <code>.Request req = 4;</code>
   * @return The req.
   */
  @Override
  public com.tequeno.netty.protobuf.Request getReq() {
    if (dataBodyCase_ == 4) {
       return (com.tequeno.netty.protobuf.Request) dataBody_;
    }
    return com.tequeno.netty.protobuf.Request.getDefaultInstance();
  }
  /**
   * <code>.Request req = 4;</code>
   */
  @Override
  public com.tequeno.netty.protobuf.RequestOrBuilder getReqOrBuilder() {
    if (dataBodyCase_ == 4) {
       return (com.tequeno.netty.protobuf.Request) dataBody_;
    }
    return com.tequeno.netty.protobuf.Request.getDefaultInstance();
  }

  public static final int RES_FIELD_NUMBER = 5;
  /**
   * <code>.Response res = 5;</code>
   * @return Whether the res field is set.
   */
  @Override
  public boolean hasRes() {
    return dataBodyCase_ == 5;
  }
  /**
   * <code>.Response res = 5;</code>
   * @return The res.
   */
  @Override
  public com.tequeno.netty.protobuf.Response getRes() {
    if (dataBodyCase_ == 5) {
       return (com.tequeno.netty.protobuf.Response) dataBody_;
    }
    return com.tequeno.netty.protobuf.Response.getDefaultInstance();
  }
  /**
   * <code>.Response res = 5;</code>
   */
  @Override
  public com.tequeno.netty.protobuf.ResponseOrBuilder getResOrBuilder() {
    if (dataBodyCase_ == 5) {
       return (com.tequeno.netty.protobuf.Response) dataBody_;
    }
    return com.tequeno.netty.protobuf.Response.getDefaultInstance();
  }

  public static final int REQUESTLIST_FIELD_NUMBER = 6;
  private java.util.List<com.tequeno.netty.protobuf.Request> requestList_;
  /**
   * <pre>
   * 集合
   * </pre>
   *
   * <code>repeated .Request requestList = 6;</code>
   */
  @Override
  public java.util.List<com.tequeno.netty.protobuf.Request> getRequestListList() {
    return requestList_;
  }
  /**
   * <pre>
   * 集合
   * </pre>
   *
   * <code>repeated .Request requestList = 6;</code>
   */
  @Override
  public java.util.List<? extends com.tequeno.netty.protobuf.RequestOrBuilder>
      getRequestListOrBuilderList() {
    return requestList_;
  }
  /**
   * <pre>
   * 集合
   * </pre>
   *
   * <code>repeated .Request requestList = 6;</code>
   */
  @Override
  public int getRequestListCount() {
    return requestList_.size();
  }
  /**
   * <pre>
   * 集合
   * </pre>
   *
   * <code>repeated .Request requestList = 6;</code>
   */
  @Override
  public com.tequeno.netty.protobuf.Request getRequestList(int index) {
    return requestList_.get(index);
  }
  /**
   * <pre>
   * 集合
   * </pre>
   *
   * <code>repeated .Request requestList = 6;</code>
   */
  @Override
  public com.tequeno.netty.protobuf.RequestOrBuilder getRequestListOrBuilder(
      int index) {
    return requestList_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (dataType_ != com.tequeno.netty.protobuf.Wrapper.DataType.REQ.getNumber()) {
      output.writeEnum(1, dataType_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(code_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, code_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(msg_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, msg_);
    }
    if (dataBodyCase_ == 4) {
      output.writeMessage(4, (com.tequeno.netty.protobuf.Request) dataBody_);
    }
    if (dataBodyCase_ == 5) {
      output.writeMessage(5, (com.tequeno.netty.protobuf.Response) dataBody_);
    }
    for (int i = 0; i < requestList_.size(); i++) {
      output.writeMessage(6, requestList_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (dataType_ != com.tequeno.netty.protobuf.Wrapper.DataType.REQ.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, dataType_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(code_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, code_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(msg_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, msg_);
    }
    if (dataBodyCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, (com.tequeno.netty.protobuf.Request) dataBody_);
    }
    if (dataBodyCase_ == 5) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, (com.tequeno.netty.protobuf.Response) dataBody_);
    }
    for (int i = 0; i < requestList_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, requestList_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.tequeno.netty.protobuf.Wrapper)) {
      return super.equals(obj);
    }
    com.tequeno.netty.protobuf.Wrapper other = (com.tequeno.netty.protobuf.Wrapper) obj;

    if (dataType_ != other.dataType_) return false;
    if (!getCode()
        .equals(other.getCode())) return false;
    if (!getMsg()
        .equals(other.getMsg())) return false;
    if (!getRequestListList()
        .equals(other.getRequestListList())) return false;
    if (!getDataBodyCase().equals(other.getDataBodyCase())) return false;
    switch (dataBodyCase_) {
      case 4:
        if (!getReq()
            .equals(other.getReq())) return false;
        break;
      case 5:
        if (!getRes()
            .equals(other.getRes())) return false;
        break;
      case 0:
      default:
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DATATYPE_FIELD_NUMBER;
    hash = (53 * hash) + dataType_;
    hash = (37 * hash) + CODE_FIELD_NUMBER;
    hash = (53 * hash) + getCode().hashCode();
    hash = (37 * hash) + MSG_FIELD_NUMBER;
    hash = (53 * hash) + getMsg().hashCode();
    if (getRequestListCount() > 0) {
      hash = (37 * hash) + REQUESTLIST_FIELD_NUMBER;
      hash = (53 * hash) + getRequestListList().hashCode();
    }
    switch (dataBodyCase_) {
      case 4:
        hash = (37 * hash) + REQ_FIELD_NUMBER;
        hash = (53 * hash) + getReq().hashCode();
        break;
      case 5:
        hash = (37 * hash) + RES_FIELD_NUMBER;
        hash = (53 * hash) + getRes().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.tequeno.netty.protobuf.Wrapper parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tequeno.netty.protobuf.Wrapper parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tequeno.netty.protobuf.Wrapper parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tequeno.netty.protobuf.Wrapper parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tequeno.netty.protobuf.Wrapper parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tequeno.netty.protobuf.Wrapper parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tequeno.netty.protobuf.Wrapper parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.tequeno.netty.protobuf.Wrapper parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.tequeno.netty.protobuf.Wrapper parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.tequeno.netty.protobuf.Wrapper parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.tequeno.netty.protobuf.Wrapper parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.tequeno.netty.protobuf.Wrapper parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.tequeno.netty.protobuf.Wrapper prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 其他message的管理者
   * </pre>
   *
   * Protobuf type {@code Wrapper}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Wrapper)
      com.tequeno.netty.protobuf.WrapperOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tequeno.netty.protobuf.NettyMsg.internal_static_Wrapper_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tequeno.netty.protobuf.NettyMsg.internal_static_Wrapper_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tequeno.netty.protobuf.Wrapper.class, com.tequeno.netty.protobuf.Wrapper.Builder.class);
    }

    // Construct using com.tequeno.netty.protobuf.Wrapper.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getRequestListFieldBuilder();
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      dataType_ = 0;

      code_ = "";

      msg_ = "";

      if (requestListBuilder_ == null) {
        requestList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        requestListBuilder_.clear();
      }
      dataBodyCase_ = 0;
      dataBody_ = null;
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.tequeno.netty.protobuf.NettyMsg.internal_static_Wrapper_descriptor;
    }

    @Override
    public com.tequeno.netty.protobuf.Wrapper getDefaultInstanceForType() {
      return com.tequeno.netty.protobuf.Wrapper.getDefaultInstance();
    }

    @Override
    public com.tequeno.netty.protobuf.Wrapper build() {
      com.tequeno.netty.protobuf.Wrapper result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public com.tequeno.netty.protobuf.Wrapper buildPartial() {
      com.tequeno.netty.protobuf.Wrapper result = new com.tequeno.netty.protobuf.Wrapper(this);
      int from_bitField0_ = bitField0_;
      result.dataType_ = dataType_;
      result.code_ = code_;
      result.msg_ = msg_;
      if (dataBodyCase_ == 4) {
        if (reqBuilder_ == null) {
          result.dataBody_ = dataBody_;
        } else {
          result.dataBody_ = reqBuilder_.build();
        }
      }
      if (dataBodyCase_ == 5) {
        if (resBuilder_ == null) {
          result.dataBody_ = dataBody_;
        } else {
          result.dataBody_ = resBuilder_.build();
        }
      }
      if (requestListBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          requestList_ = java.util.Collections.unmodifiableList(requestList_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.requestList_ = requestList_;
      } else {
        result.requestList_ = requestListBuilder_.build();
      }
      result.dataBodyCase_ = dataBodyCase_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.tequeno.netty.protobuf.Wrapper) {
        return mergeFrom((com.tequeno.netty.protobuf.Wrapper)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.tequeno.netty.protobuf.Wrapper other) {
      if (other == com.tequeno.netty.protobuf.Wrapper.getDefaultInstance()) return this;
      if (other.dataType_ != 0) {
        setDataTypeValue(other.getDataTypeValue());
      }
      if (!other.getCode().isEmpty()) {
        code_ = other.code_;
        onChanged();
      }
      if (!other.getMsg().isEmpty()) {
        msg_ = other.msg_;
        onChanged();
      }
      if (requestListBuilder_ == null) {
        if (!other.requestList_.isEmpty()) {
          if (requestList_.isEmpty()) {
            requestList_ = other.requestList_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureRequestListIsMutable();
            requestList_.addAll(other.requestList_);
          }
          onChanged();
        }
      } else {
        if (!other.requestList_.isEmpty()) {
          if (requestListBuilder_.isEmpty()) {
            requestListBuilder_.dispose();
            requestListBuilder_ = null;
            requestList_ = other.requestList_;
            bitField0_ = (bitField0_ & ~0x00000001);
            requestListBuilder_ =
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getRequestListFieldBuilder() : null;
          } else {
            requestListBuilder_.addAllMessages(other.requestList_);
          }
        }
      }
      switch (other.getDataBodyCase()) {
        case REQ: {
          mergeReq(other.getReq());
          break;
        }
        case RES: {
          mergeRes(other.getRes());
          break;
        }
        case DATABODY_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.tequeno.netty.protobuf.Wrapper parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.tequeno.netty.protobuf.Wrapper) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int dataBodyCase_ = 0;
    private Object dataBody_;
    public DataBodyCase
        getDataBodyCase() {
      return DataBodyCase.forNumber(
          dataBodyCase_);
    }

    public Builder clearDataBody() {
      dataBodyCase_ = 0;
      dataBody_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private int dataType_ = 0;
    /**
     * <pre>
     * 设置数据的类型 方便得到数据后根据类型判断 非必要
     * </pre>
     *
     * <code>.Wrapper.DataType dataType = 1;</code>
     * @return The enum numeric value on the wire for dataType.
     */
    @Override public int getDataTypeValue() {
      return dataType_;
    }
    /**
     * <pre>
     * 设置数据的类型 方便得到数据后根据类型判断 非必要
     * </pre>
     *
     * <code>.Wrapper.DataType dataType = 1;</code>
     * @param value The enum numeric value on the wire for dataType to set.
     * @return This builder for chaining.
     */
    public Builder setDataTypeValue(int value) {

      dataType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 设置数据的类型 方便得到数据后根据类型判断 非必要
     * </pre>
     *
     * <code>.Wrapper.DataType dataType = 1;</code>
     * @return The dataType.
     */
    @Override
    public com.tequeno.netty.protobuf.Wrapper.DataType getDataType() {
      @SuppressWarnings("deprecation")
      com.tequeno.netty.protobuf.Wrapper.DataType result = com.tequeno.netty.protobuf.Wrapper.DataType.valueOf(dataType_);
      return result == null ? com.tequeno.netty.protobuf.Wrapper.DataType.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * 设置数据的类型 方便得到数据后根据类型判断 非必要
     * </pre>
     *
     * <code>.Wrapper.DataType dataType = 1;</code>
     * @param value The dataType to set.
     * @return This builder for chaining.
     */
    public Builder setDataType(com.tequeno.netty.protobuf.Wrapper.DataType value) {
      if (value == null) {
        throw new NullPointerException();
      }

      dataType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 设置数据的类型 方便得到数据后根据类型判断 非必要
     * </pre>
     *
     * <code>.Wrapper.DataType dataType = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearDataType() {

      dataType_ = 0;
      onChanged();
      return this;
    }

    private Object code_ = "";
    /**
     * <code>string code = 2;</code>
     * @return The code.
     */
    public String getCode() {
      Object ref = code_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        code_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string code = 2;</code>
     * @return The bytes for code.
     */
    public com.google.protobuf.ByteString
        getCodeBytes() {
      Object ref = code_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        code_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string code = 2;</code>
     * @param value The code to set.
     * @return This builder for chaining.
     */
    public Builder setCode(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      code_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string code = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearCode() {

      code_ = getDefaultInstance().getCode();
      onChanged();
      return this;
    }
    /**
     * <code>string code = 2;</code>
     * @param value The bytes for code to set.
     * @return This builder for chaining.
     */
    public Builder setCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      code_ = value;
      onChanged();
      return this;
    }

    private Object msg_ = "";
    /**
     * <code>string msg = 3;</code>
     * @return The msg.
     */
    public String getMsg() {
      Object ref = msg_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        msg_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string msg = 3;</code>
     * @return The bytes for msg.
     */
    public com.google.protobuf.ByteString
        getMsgBytes() {
      Object ref = msg_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        msg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string msg = 3;</code>
     * @param value The msg to set.
     * @return This builder for chaining.
     */
    public Builder setMsg(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      msg_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string msg = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearMsg() {

      msg_ = getDefaultInstance().getMsg();
      onChanged();
      return this;
    }
    /**
     * <code>string msg = 3;</code>
     * @param value The bytes for msg to set.
     * @return This builder for chaining.
     */
    public Builder setMsgBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      msg_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.tequeno.netty.protobuf.Request, com.tequeno.netty.protobuf.Request.Builder, com.tequeno.netty.protobuf.RequestOrBuilder> reqBuilder_;
    /**
     * <code>.Request req = 4;</code>
     * @return Whether the req field is set.
     */
    @Override
    public boolean hasReq() {
      return dataBodyCase_ == 4;
    }
    /**
     * <code>.Request req = 4;</code>
     * @return The req.
     */
    @Override
    public com.tequeno.netty.protobuf.Request getReq() {
      if (reqBuilder_ == null) {
        if (dataBodyCase_ == 4) {
          return (com.tequeno.netty.protobuf.Request) dataBody_;
        }
        return com.tequeno.netty.protobuf.Request.getDefaultInstance();
      } else {
        if (dataBodyCase_ == 4) {
          return reqBuilder_.getMessage();
        }
        return com.tequeno.netty.protobuf.Request.getDefaultInstance();
      }
    }
    /**
     * <code>.Request req = 4;</code>
     */
    public Builder setReq(com.tequeno.netty.protobuf.Request value) {
      if (reqBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        dataBody_ = value;
        onChanged();
      } else {
        reqBuilder_.setMessage(value);
      }
      dataBodyCase_ = 4;
      return this;
    }
    /**
     * <code>.Request req = 4;</code>
     */
    public Builder setReq(
        com.tequeno.netty.protobuf.Request.Builder builderForValue) {
      if (reqBuilder_ == null) {
        dataBody_ = builderForValue.build();
        onChanged();
      } else {
        reqBuilder_.setMessage(builderForValue.build());
      }
      dataBodyCase_ = 4;
      return this;
    }
    /**
     * <code>.Request req = 4;</code>
     */
    public Builder mergeReq(com.tequeno.netty.protobuf.Request value) {
      if (reqBuilder_ == null) {
        if (dataBodyCase_ == 4 &&
            dataBody_ != com.tequeno.netty.protobuf.Request.getDefaultInstance()) {
          dataBody_ = com.tequeno.netty.protobuf.Request.newBuilder((com.tequeno.netty.protobuf.Request) dataBody_)
              .mergeFrom(value).buildPartial();
        } else {
          dataBody_ = value;
        }
        onChanged();
      } else {
        if (dataBodyCase_ == 4) {
          reqBuilder_.mergeFrom(value);
        }
        reqBuilder_.setMessage(value);
      }
      dataBodyCase_ = 4;
      return this;
    }
    /**
     * <code>.Request req = 4;</code>
     */
    public Builder clearReq() {
      if (reqBuilder_ == null) {
        if (dataBodyCase_ == 4) {
          dataBodyCase_ = 0;
          dataBody_ = null;
          onChanged();
        }
      } else {
        if (dataBodyCase_ == 4) {
          dataBodyCase_ = 0;
          dataBody_ = null;
        }
        reqBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.Request req = 4;</code>
     */
    public com.tequeno.netty.protobuf.Request.Builder getReqBuilder() {
      return getReqFieldBuilder().getBuilder();
    }
    /**
     * <code>.Request req = 4;</code>
     */
    @Override
    public com.tequeno.netty.protobuf.RequestOrBuilder getReqOrBuilder() {
      if ((dataBodyCase_ == 4) && (reqBuilder_ != null)) {
        return reqBuilder_.getMessageOrBuilder();
      } else {
        if (dataBodyCase_ == 4) {
          return (com.tequeno.netty.protobuf.Request) dataBody_;
        }
        return com.tequeno.netty.protobuf.Request.getDefaultInstance();
      }
    }
    /**
     * <code>.Request req = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.tequeno.netty.protobuf.Request, com.tequeno.netty.protobuf.Request.Builder, com.tequeno.netty.protobuf.RequestOrBuilder>
        getReqFieldBuilder() {
      if (reqBuilder_ == null) {
        if (!(dataBodyCase_ == 4)) {
          dataBody_ = com.tequeno.netty.protobuf.Request.getDefaultInstance();
        }
        reqBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.tequeno.netty.protobuf.Request, com.tequeno.netty.protobuf.Request.Builder, com.tequeno.netty.protobuf.RequestOrBuilder>(
                (com.tequeno.netty.protobuf.Request) dataBody_,
                getParentForChildren(),
                isClean());
        dataBody_ = null;
      }
      dataBodyCase_ = 4;
      onChanged();;
      return reqBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.tequeno.netty.protobuf.Response, com.tequeno.netty.protobuf.Response.Builder, com.tequeno.netty.protobuf.ResponseOrBuilder> resBuilder_;
    /**
     * <code>.Response res = 5;</code>
     * @return Whether the res field is set.
     */
    @Override
    public boolean hasRes() {
      return dataBodyCase_ == 5;
    }
    /**
     * <code>.Response res = 5;</code>
     * @return The res.
     */
    @Override
    public com.tequeno.netty.protobuf.Response getRes() {
      if (resBuilder_ == null) {
        if (dataBodyCase_ == 5) {
          return (com.tequeno.netty.protobuf.Response) dataBody_;
        }
        return com.tequeno.netty.protobuf.Response.getDefaultInstance();
      } else {
        if (dataBodyCase_ == 5) {
          return resBuilder_.getMessage();
        }
        return com.tequeno.netty.protobuf.Response.getDefaultInstance();
      }
    }
    /**
     * <code>.Response res = 5;</code>
     */
    public Builder setRes(com.tequeno.netty.protobuf.Response value) {
      if (resBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        dataBody_ = value;
        onChanged();
      } else {
        resBuilder_.setMessage(value);
      }
      dataBodyCase_ = 5;
      return this;
    }
    /**
     * <code>.Response res = 5;</code>
     */
    public Builder setRes(
        com.tequeno.netty.protobuf.Response.Builder builderForValue) {
      if (resBuilder_ == null) {
        dataBody_ = builderForValue.build();
        onChanged();
      } else {
        resBuilder_.setMessage(builderForValue.build());
      }
      dataBodyCase_ = 5;
      return this;
    }
    /**
     * <code>.Response res = 5;</code>
     */
    public Builder mergeRes(com.tequeno.netty.protobuf.Response value) {
      if (resBuilder_ == null) {
        if (dataBodyCase_ == 5 &&
            dataBody_ != com.tequeno.netty.protobuf.Response.getDefaultInstance()) {
          dataBody_ = com.tequeno.netty.protobuf.Response.newBuilder((com.tequeno.netty.protobuf.Response) dataBody_)
              .mergeFrom(value).buildPartial();
        } else {
          dataBody_ = value;
        }
        onChanged();
      } else {
        if (dataBodyCase_ == 5) {
          resBuilder_.mergeFrom(value);
        }
        resBuilder_.setMessage(value);
      }
      dataBodyCase_ = 5;
      return this;
    }
    /**
     * <code>.Response res = 5;</code>
     */
    public Builder clearRes() {
      if (resBuilder_ == null) {
        if (dataBodyCase_ == 5) {
          dataBodyCase_ = 0;
          dataBody_ = null;
          onChanged();
        }
      } else {
        if (dataBodyCase_ == 5) {
          dataBodyCase_ = 0;
          dataBody_ = null;
        }
        resBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.Response res = 5;</code>
     */
    public com.tequeno.netty.protobuf.Response.Builder getResBuilder() {
      return getResFieldBuilder().getBuilder();
    }
    /**
     * <code>.Response res = 5;</code>
     */
    @Override
    public com.tequeno.netty.protobuf.ResponseOrBuilder getResOrBuilder() {
      if ((dataBodyCase_ == 5) && (resBuilder_ != null)) {
        return resBuilder_.getMessageOrBuilder();
      } else {
        if (dataBodyCase_ == 5) {
          return (com.tequeno.netty.protobuf.Response) dataBody_;
        }
        return com.tequeno.netty.protobuf.Response.getDefaultInstance();
      }
    }
    /**
     * <code>.Response res = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.tequeno.netty.protobuf.Response, com.tequeno.netty.protobuf.Response.Builder, com.tequeno.netty.protobuf.ResponseOrBuilder>
        getResFieldBuilder() {
      if (resBuilder_ == null) {
        if (!(dataBodyCase_ == 5)) {
          dataBody_ = com.tequeno.netty.protobuf.Response.getDefaultInstance();
        }
        resBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.tequeno.netty.protobuf.Response, com.tequeno.netty.protobuf.Response.Builder, com.tequeno.netty.protobuf.ResponseOrBuilder>(
                (com.tequeno.netty.protobuf.Response) dataBody_,
                getParentForChildren(),
                isClean());
        dataBody_ = null;
      }
      dataBodyCase_ = 5;
      onChanged();;
      return resBuilder_;
    }

    private java.util.List<com.tequeno.netty.protobuf.Request> requestList_ =
      java.util.Collections.emptyList();
    private void ensureRequestListIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        requestList_ = new java.util.ArrayList<com.tequeno.netty.protobuf.Request>(requestList_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.tequeno.netty.protobuf.Request, com.tequeno.netty.protobuf.Request.Builder, com.tequeno.netty.protobuf.RequestOrBuilder> requestListBuilder_;

    /**
     * <pre>
     * 集合
     * </pre>
     *
     * <code>repeated .Request requestList = 6;</code>
     */
    public java.util.List<com.tequeno.netty.protobuf.Request> getRequestListList() {
      if (requestListBuilder_ == null) {
        return java.util.Collections.unmodifiableList(requestList_);
      } else {
        return requestListBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * 集合
     * </pre>
     *
     * <code>repeated .Request requestList = 6;</code>
     */
    public int getRequestListCount() {
      if (requestListBuilder_ == null) {
        return requestList_.size();
      } else {
        return requestListBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * 集合
     * </pre>
     *
     * <code>repeated .Request requestList = 6;</code>
     */
    public com.tequeno.netty.protobuf.Request getRequestList(int index) {
      if (requestListBuilder_ == null) {
        return requestList_.get(index);
      } else {
        return requestListBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * 集合
     * </pre>
     *
     * <code>repeated .Request requestList = 6;</code>
     */
    public Builder setRequestList(
        int index, com.tequeno.netty.protobuf.Request value) {
      if (requestListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRequestListIsMutable();
        requestList_.set(index, value);
        onChanged();
      } else {
        requestListBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * 集合
     * </pre>
     *
     * <code>repeated .Request requestList = 6;</code>
     */
    public Builder setRequestList(
        int index, com.tequeno.netty.protobuf.Request.Builder builderForValue) {
      if (requestListBuilder_ == null) {
        ensureRequestListIsMutable();
        requestList_.set(index, builderForValue.build());
        onChanged();
      } else {
        requestListBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 集合
     * </pre>
     *
     * <code>repeated .Request requestList = 6;</code>
     */
    public Builder addRequestList(com.tequeno.netty.protobuf.Request value) {
      if (requestListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRequestListIsMutable();
        requestList_.add(value);
        onChanged();
      } else {
        requestListBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * 集合
     * </pre>
     *
     * <code>repeated .Request requestList = 6;</code>
     */
    public Builder addRequestList(
        int index, com.tequeno.netty.protobuf.Request value) {
      if (requestListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRequestListIsMutable();
        requestList_.add(index, value);
        onChanged();
      } else {
        requestListBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * 集合
     * </pre>
     *
     * <code>repeated .Request requestList = 6;</code>
     */
    public Builder addRequestList(
        com.tequeno.netty.protobuf.Request.Builder builderForValue) {
      if (requestListBuilder_ == null) {
        ensureRequestListIsMutable();
        requestList_.add(builderForValue.build());
        onChanged();
      } else {
        requestListBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 集合
     * </pre>
     *
     * <code>repeated .Request requestList = 6;</code>
     */
    public Builder addRequestList(
        int index, com.tequeno.netty.protobuf.Request.Builder builderForValue) {
      if (requestListBuilder_ == null) {
        ensureRequestListIsMutable();
        requestList_.add(index, builderForValue.build());
        onChanged();
      } else {
        requestListBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 集合
     * </pre>
     *
     * <code>repeated .Request requestList = 6;</code>
     */
    public Builder addAllRequestList(
        Iterable<? extends com.tequeno.netty.protobuf.Request> values) {
      if (requestListBuilder_ == null) {
        ensureRequestListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, requestList_);
        onChanged();
      } else {
        requestListBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * 集合
     * </pre>
     *
     * <code>repeated .Request requestList = 6;</code>
     */
    public Builder clearRequestList() {
      if (requestListBuilder_ == null) {
        requestList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        requestListBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * 集合
     * </pre>
     *
     * <code>repeated .Request requestList = 6;</code>
     */
    public Builder removeRequestList(int index) {
      if (requestListBuilder_ == null) {
        ensureRequestListIsMutable();
        requestList_.remove(index);
        onChanged();
      } else {
        requestListBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * 集合
     * </pre>
     *
     * <code>repeated .Request requestList = 6;</code>
     */
    public com.tequeno.netty.protobuf.Request.Builder getRequestListBuilder(
        int index) {
      return getRequestListFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * 集合
     * </pre>
     *
     * <code>repeated .Request requestList = 6;</code>
     */
    public com.tequeno.netty.protobuf.RequestOrBuilder getRequestListOrBuilder(
        int index) {
      if (requestListBuilder_ == null) {
        return requestList_.get(index);  } else {
        return requestListBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * 集合
     * </pre>
     *
     * <code>repeated .Request requestList = 6;</code>
     */
    public java.util.List<? extends com.tequeno.netty.protobuf.RequestOrBuilder>
         getRequestListOrBuilderList() {
      if (requestListBuilder_ != null) {
        return requestListBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(requestList_);
      }
    }
    /**
     * <pre>
     * 集合
     * </pre>
     *
     * <code>repeated .Request requestList = 6;</code>
     */
    public com.tequeno.netty.protobuf.Request.Builder addRequestListBuilder() {
      return getRequestListFieldBuilder().addBuilder(
          com.tequeno.netty.protobuf.Request.getDefaultInstance());
    }
    /**
     * <pre>
     * 集合
     * </pre>
     *
     * <code>repeated .Request requestList = 6;</code>
     */
    public com.tequeno.netty.protobuf.Request.Builder addRequestListBuilder(
        int index) {
      return getRequestListFieldBuilder().addBuilder(
          index, com.tequeno.netty.protobuf.Request.getDefaultInstance());
    }
    /**
     * <pre>
     * 集合
     * </pre>
     *
     * <code>repeated .Request requestList = 6;</code>
     */
    public java.util.List<com.tequeno.netty.protobuf.Request.Builder>
         getRequestListBuilderList() {
      return getRequestListFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.tequeno.netty.protobuf.Request, com.tequeno.netty.protobuf.Request.Builder, com.tequeno.netty.protobuf.RequestOrBuilder>
        getRequestListFieldBuilder() {
      if (requestListBuilder_ == null) {
        requestListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.tequeno.netty.protobuf.Request, com.tequeno.netty.protobuf.Request.Builder, com.tequeno.netty.protobuf.RequestOrBuilder>(
                requestList_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        requestList_ = null;
      }
      return requestListBuilder_;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Wrapper)
  }

  // @@protoc_insertion_point(class_scope:Wrapper)
  private static final com.tequeno.netty.protobuf.Wrapper DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.tequeno.netty.protobuf.Wrapper();
  }

  public static com.tequeno.netty.protobuf.Wrapper getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Wrapper>
      PARSER = new com.google.protobuf.AbstractParser<Wrapper>() {
    @Override
    public Wrapper parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Wrapper(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Wrapper> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<Wrapper> getParserForType() {
    return PARSER;
  }

  @Override
  public com.tequeno.netty.protobuf.Wrapper getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

