server:
  port: 7210
  servlet:
    context-path: /
spring:
  application:
    name: viva-boot
  profiles:
    active: dev
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 15
      max-lifetime: 12000
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://rm-bp1x1ty88kmp5ypp5go.mysql.rds.aliyuncs.com:3306/school_call_test
#    username: school_call_test
#    password: Aa123456#

#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/viva-la-vida
#    username: a00c8f12
#    password: d0633c

    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:/plugin/sqlite-x64/test.db
# redis
redis:
  host: 127.0.0.1
  password: d40df8
  port: 6379
  database: 0
  timeout: 10000
  # 连接耗尽时是否阻塞, false报异常,true阻塞直到超时, 默认true
  block-when-exhausted: false
  # 是否启用pool的jmx管理功能, 默认true
  jmx-enabled: false
  # 链接池配置
  min-idle: 0
  max-idle: 8
  max-active: 256
  max-wait: 5000
# rocketmq
rocketmq:
  adder: 127.0.0.1:9876
  producer:
    group: r_group_p
    instance: r_instance_p
    retryTimesWhenSendFailed: 2
    retryTimesWhenSendAsyncFailed: 2
    vipChannelEnabled: false
    sendMsgTimeout: 3000
    maxMessageSize: 4194304
  consumer:
    group: r_group_c
    instance:  r_instance_c
    #    最大重复消费次数
    maxReconsumeTimes: 3
    #    消费者一次接收消息最大数量
    consumeMessageBatchMaxSize: 10
    consumeTimeout: 3000
    consumeThreadMin: 10
    consumeThreadMax: 30
# rabbitmq
rabbitmq:
  username: 391d93
  password: e233e4
  host: 127.0.0.1
  port: 5672
  virtualHost: v_host_1
#启动参数
#-Dspring.config.location=/data/deploy/viva-boot/